"""add_agent_runtime_url

Revision ID: 1a1d63db9168
Revises: a652a160470d
Create Date: 2026-04-03 18:17:30.146840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1d63db9168'
down_revision: Union[str, None] = 'a652a160470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('runtime_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'runtime_url')
    # ### end Alembic commands ###
