"""add_connection_type_and_http_config

Revision ID: 43f0e18ac6f0
Revises: 1a1d63db9168
Create Date: 2026-04-03 19:47:34.515583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f0e18ac6f0'
down_revision: Union[str, None] = '1a1d63db9168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('agents', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Add as nullable first, backfill, then add NOT NULL default
    op.add_column('salesforce_connections', sa.Column('connection_type', sa.Text(), nullable=True))
    op.execute("UPDATE salesforce_connections SET connection_type = 'salesforce' WHERE connection_type IS NULL")
    op.alter_column('salesforce_connections', 'connection_type', nullable=False, server_default='salesforce')
    op.add_column('salesforce_connections', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesforce_connections', 'config')
    op.drop_column('salesforce_connections', 'connection_type')
    op.drop_column('agents', 'config')
    # ### end Alembic commands ###
