"""phase8_baseline_regression

Revision ID: e3cc3cd244fa
Revises: 896d5a2c1f27
Create Date: 2026-04-03 13:28:18.061576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cc3cd244fa'
down_revision: Union[str, None] = '896d5a2c1f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiating_questions', sa.Column('expected_answer', sa.Text(), nullable=True))
    op.add_column('test_run_results', sa.Column('human_score', sa.Integer(), nullable=True))
    op.add_column('test_run_results', sa.Column('human_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_run_results', 'human_notes')
    op.drop_column('test_run_results', 'human_score')
    op.drop_column('initiating_questions', 'expected_answer')
    # ### end Alembic commands ###
